apiVersion: v1
kind: ConfigMap
metadata:
  name: multitool-maps
  namespace: netology-8
data:
  HTTP_PORT: "1180"
  index.html: |
    <html>
    <h1>Hey Hetology!</h1>
    </br>
    <h1>Test custom page</h1>
    </html>
