apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-dep-1
  namespace: netology-4
spec:
  selector:
    matchLabels:
      app: netdep
  replicas: 3
  template:
    metadata:
      labels:
        app: netdep
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.0
          ports:
            - containerPort: 80
        - name: multitool
          image: wbitt/network-multitool
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "1180"
