apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
  namespace: netology-4
spec:
  type: NodePort
  selector:
    app: netdep
  ports:
    - port: 80
      name: nginx-port
      targetPort: 80
      nodePort: 30001
    - port: 8080
      name: multitool-port
      targetPort: 1180
      nodePort: 30002
