apiVersion: v1
kind: Service
metadata:
  name: network-service-1
  namespace: netology-4
spec:
  selector:
    app: netdep
  ports:
    - protocol: TCP
      name: nginx
      port: 9001
      targetPort: 80
    - protocol: TCP
      name: multitool
      port: 9002
      targetPort: 1180
