---
- name: restart vector
  become_method: sudo
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
  when: vector_service_state != 'stopped'
- name: reload vector
  ansible.builtin.systemd:
    name: vector
    state: restart
  when: vector_service_state != 'stopped'
