apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-volume
  namespace: netology-7
spec:
  selector:
    matchLabels:
      app: volume
  replicas: 1
  template:
    metadata:
      labels:
        app: volume
    spec:
      containers:
        - name: busybox
          image: busybox:1.36.1
          command:
            [
              "sh",
              "-c",
              watch -n5 "echo 'Hello Netology!' >> /output/testlog.txt",
            ]
          volumeMounts:
            - name: volume
              mountPath: /output
        - name: multitool
          image: wbitt/network-multitool
          command: ["sh", "-c", "tail -f /output/testlog.txt"]
          volumeMounts:
            - name: volume
              mountPath: /output
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pvc-vol
