apiVersion: v1
kind: Service
metadata:
  name: diplom-svc
  namespace: diplom-static-site
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30051
