{
 "title": "Homework board",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job='node'}",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "CPULA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_load1{job=\"node\"}",
     "legendFormat": "load 1"
    },
    {
     "expr": "node_load5{job=\"node\"}",
     "legendFormat": "load 5"
    },
    {
     "expr": "node_load15{job=\"node\"}",
     "legendFormat": "load 15"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/vda2\", fstype=\"ext4\", instance=\"node-exporter:9100\", job=\"node\", mountpoint=\"/\"}",
     "legendFormat": "filesystem size"
    }
   ]
  }
 ]
}